-- Plan-level module entitlements (subscription features)
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "modules" JSONB;

-- Extend FeatureModule enum for support sub-features
ALTER TYPE "FeatureModule" ADD VALUE IF NOT EXISTS 'SUPPORT_INBOX';
ALTER TYPE "FeatureModule" ADD VALUE IF NOT EXISTS 'SUPPORT_SLA';
ALTER TYPE "FeatureModule" ADD VALUE IF NOT EXISTS 'SUPPORT_LIVE_CHAT';
ALTER TYPE "FeatureModule" ADD VALUE IF NOT EXISTS 'SUPPORT_KNOWLEDGE';
ALTER TYPE "FeatureModule" ADD VALUE IF NOT EXISTS 'SUPPORT_CANNED';
ALTER TYPE "FeatureModule" ADD VALUE IF NOT EXISTS 'SUPPORT_GROUPS';
ALTER TYPE "FeatureModule" ADD VALUE IF NOT EXISTS 'TICKET_ADVANCED';
