-- AlterTable
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "lineItems" JSONB;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3);
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "receivedAt" TIMESTAMP(3);

ALTER TABLE "SalesOrder" ADD COLUMN IF NOT EXISTS "lineItems" JSONB;
ALTER TABLE "SalesOrder" ADD COLUMN IF NOT EXISTS "notes" TEXT;
