import type { IndustryVerticalPack } from '@/lib/industry-packs/types';

export const AUTOMOTIVE_PACK: IndustryVerticalPack = {
  id: 'automotive',
  label: 'Automotive',
  description: 'Workshops, fleet service, warranties, and dealer after-sales.',
  pack: 'field_service',
  terminologyOverrides: {
    customer: 'Customer / fleet',
    customers: 'Customers / fleets',
    agent: 'Service advisor',
    asset: 'Vehicle',
    equipment: 'Vehicles',
    ticket: 'Service job',
    tickets: 'Service jobs',
    lead: 'Walk-in / lead',
    leads: 'Leads',
    deal: 'Job / deal',
    deals: 'Jobs / deals',
    newRequest: 'Book service',
    portalSubtitle: 'Track service jobs, warranties, and vehicle history.',
  },
  includeBaseTicketTypes: true,
  includeVerticalTicketTypes: true,
  ticketTypes: [
    {
      id: 'service_job',
      label: 'Service job / RO',
      description: 'Workshop repair order or service appointment.',
      defaultPriority: 'HIGH',
      groupName: 'Workshop',
      showEquipment: true,
      fields: [
        { id: 'vehicleId', label: 'VIN / reg. no.', type: 'text', placeholder: 'Optional' },
      ],
    },
    {
      id: 'vehicle_issue',
      label: 'Vehicle / unit fault',
      description: 'Fault reported on a vehicle or installed unit.',
      defaultPriority: 'HIGH',
      groupName: 'Workshop',
      showEquipment: true,
      fields: [],
    },
    {
      id: 'warranty_claim',
      label: 'Warranty claim',
      description: 'OEM or dealer warranty repair.',
      defaultPriority: 'MEDIUM',
      groupName: 'Workshop',
      showEquipment: true,
      fields: [],
    },
    {
      id: 'body_paint',
      label: 'Body & paint',
      description: 'Collision, dent, or paint work.',
      defaultPriority: 'MEDIUM',
      groupName: 'Workshop',
      showEquipment: true,
      fields: [],
    },
  ],
  slaByPriority: {
    CRITICAL: { responseHours: 2, resolutionHours: 24 },
    HIGH: { responseHours: 4, resolutionHours: 48 },
    MEDIUM: { responseHours: 24, resolutionHours: 72 },
    LOW: { responseHours: 72, resolutionHours: 120 },
  },
  homeWidgets: ['renewals', 'sla_at_risk'],
};
