import type { IndustryVerticalPack } from '@/lib/industry-packs/types';

export const FACILITIES_MANAGEMENT_PACK: IndustryVerticalPack = {
  id: 'facilities_management',
  label: 'Facilities Management',
  description: 'Sites, work orders, technicians, and on-site service operations.',
  pack: 'field_service',
  terminologyOverrides: {
    customer: 'Site / client',
    customers: 'Sites / clients',
    agent: 'Technician',
    asset: 'Site asset',
    equipment: 'Assets',
    ticket: 'Work order',
    tickets: 'Work orders',
    lead: 'Site lead',
    leads: 'Site leads',
    deal: 'Contract',
    deals: 'Contracts',
    newRequest: 'New work order',
    portalSubtitle: 'Submit work orders and track facility service.',
  },
  includeBaseTicketTypes: true,
  includeVerticalTicketTypes: false,
  ticketTypes: [
    {
      id: 'housekeeping',
      label: 'Housekeeping',
      description: 'Cleaning, soft services, or janitorial request.',
      defaultPriority: 'MEDIUM',
      groupName: 'Facilities',
      fields: [
        {
          id: 'siteArea',
          label: 'Site / area',
          type: 'text',
          placeholder: 'Building, floor, zone',
        },
      ],
    },
    {
      id: 'mep',
      label: 'MEP (Mechanical, Electrical, Plumbing)',
      description: 'MEP fault or maintenance request.',
      defaultPriority: 'HIGH',
      groupName: 'Facilities',
      showEquipment: true,
      fields: [
        {
          id: 'siteArea',
          label: 'Site / area',
          type: 'text',
          required: true,
        },
      ],
    },
    {
      id: 'security',
      label: 'Security',
      description: 'Security incident or access control issue.',
      defaultPriority: 'HIGH',
      groupName: 'Security',
      fields: [],
    },
    {
      id: 'pest_control',
      label: 'Pest Control',
      description: 'Pest control visit or escalation.',
      defaultPriority: 'MEDIUM',
      groupName: 'Facilities',
      fields: [],
    },
    {
      id: 'landscaping',
      label: 'Landscaping',
      description: 'Grounds or landscaping work order.',
      defaultPriority: 'LOW',
      groupName: 'Facilities',
      fields: [],
    },
    {
      id: 'civil_maintenance',
      label: 'Civil Maintenance',
      description: 'Civil / building maintenance request.',
      defaultPriority: 'MEDIUM',
      groupName: 'Facilities',
      fields: [
        {
          id: 'siteArea',
          label: 'Site / area',
          type: 'text',
          placeholder: 'Building, floor, zone',
        },
      ],
    },
    {
      id: 'work_order',
      label: 'Work order',
      description: 'General on-site repair or inspection.',
      defaultPriority: 'HIGH',
      groupName: 'Facilities',
      showEquipment: true,
      fields: [
        {
          id: 'siteArea',
          label: 'Site / area',
          type: 'text',
          placeholder: 'Building, floor, zone',
        },
      ],
    },
  ],
  slaByPriority: {
    CRITICAL: { responseHours: 4, resolutionHours: 24 },
    HIGH: { responseHours: 8, resolutionHours: 48 },
    MEDIUM: { responseHours: 24, resolutionHours: 72 },
    LOW: { responseHours: 72, resolutionHours: 120 },
  },
  homeWidgets: ['open_work_orders', 'sla_at_risk', 'renewals'],
};
