import type { IndustryVerticalPack } from '@/lib/industry-packs/types';

export const LOGISTICS_PACK: IndustryVerticalPack = {
  id: 'logistics',
  label: 'Logistics',
  description: 'Fleet assets, inventory, B2B accounts, and ops support.',
  pack: 'manufacturing',
  terminologyOverrides: {
    customer: 'Shipper / partner',
    customers: 'Shippers / partners',
    agent: 'Ops coordinator',
    asset: 'Fleet asset',
    equipment: 'Fleet & assets',
    ticket: 'Ops ticket',
    tickets: 'Ops tickets',
    lead: 'Lane lead',
    leads: 'Lane leads',
    deal: 'Contract',
    deals: 'Contracts',
    portalSubtitle: 'Track shipments support, assets, and account activity.',
  },
  featureOverrides: {
    fieldService: true,
  },
  includeBaseTicketTypes: true,
  includeVerticalTicketTypes: false,
  ticketTypes: [
    {
      id: 'vehicle_breakdown',
      label: 'Vehicle Breakdown',
      description: 'Vehicle or fleet unit breakdown.',
      defaultPriority: 'CRITICAL',
      groupName: 'Fleet',
      showEquipment: true,
      fields: [
        {
          id: 'vehicleId',
          label: 'Vehicle / reg. no.',
          type: 'text',
          required: true,
        },
      ],
    },
    {
      id: 'scheduled_maintenance',
      label: 'Scheduled Maintenance',
      description: 'Planned fleet or equipment service.',
      defaultPriority: 'MEDIUM',
      groupName: 'Fleet',
      showEquipment: true,
      fields: [],
    },
    {
      id: 'customer_complaint',
      label: 'Customer Complaint',
      description: 'Shipper or consignee complaint.',
      defaultPriority: 'HIGH',
      groupName: 'Operations',
      fields: [],
    },
    {
      id: 'delivery',
      label: 'Delivery Issue',
      description: 'Failed delivery, delay, or POD dispute.',
      defaultPriority: 'HIGH',
      groupName: 'Operations',
      fields: [
        {
          id: 'trackingNumber',
          label: 'Tracking / AWB',
          type: 'text',
          required: true,
        },
      ],
    },
    {
      id: 'driver_incident',
      label: 'Driver Incident',
      description: 'Driver safety, conduct, or route incident.',
      defaultPriority: 'HIGH',
      groupName: 'Operations',
      fields: [],
    },
    {
      id: 'vendor_escalation',
      label: 'Vendor Escalation',
      description: '3PL or vendor performance escalation.',
      defaultPriority: 'HIGH',
      groupName: 'Operations',
      fields: [],
    },
    {
      id: 'shipment',
      label: 'Shipment issue',
      description: 'Delayed, damaged, or missing shipment.',
      defaultPriority: 'HIGH',
      groupName: 'Operations',
      fields: [
        {
          id: 'trackingNumber',
          label: 'Tracking / AWB',
          type: 'text',
          required: true,
        },
      ],
    },
  ],
  slaByPriority: {
    CRITICAL: { responseHours: 2, resolutionHours: 8 },
    HIGH: { responseHours: 4, resolutionHours: 24 },
    MEDIUM: { responseHours: 12, resolutionHours: 48 },
    LOW: { responseHours: 48, resolutionHours: 96 },
  },
  homeWidgets: ['delivery_exceptions', 'sla_at_risk', 'renewals'],
};
